[package]
name = "mpris"
description = "Idiomatic MPRIS D-Bus interface library"
version = "2.0.0-rc2"
license = "Apache-2.0"
edition = "2018"
authors = ["Magnus Bergmark <magnus.bergmark@gmail.com>"]
repository = "https://github.com/Mange/mpris-rs"
readme = "README.md"
categories = ["api-bindings", "multimedia", "os::unix-apis"]
keywords = ["dbus", "mpris"]

[badges]
travis-ci = { repository = "Mange/mpris-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
dbus = "0.8.1"
failure = "0.1.5"
failure_derive = "0.1.5"
enum-kinds = "0.4.1"
derive_is_enum_variant = "0.1.1"
from_variants = "0.4.0"

# For examples
[dev-dependencies]
termion = "1.5.1"
